# ----------------------------------------------------------------------------------------------
# create KINSHIP MATRIX

module load R
library(kinship)
ped <- read.csv("PEDFILE", header=T, sep=",")
kmat <-makekinship(ped$famid,ped$id,ped$fa,ped$mo)
kmat <- kmat*2
save(kmat, file="KINSHIP_MATRIX.RData")

#GWAF package does not work for the kinship matrix generated by the following method. But, the following method of pedigree generation could be used for error checking
#library(kinship2)
#ped <- read.csv("PEDFILE", header=T, sep=",")
#pedall <- pedigree(id=ped$id, dadid=ped$fa, momid=ped$mo, sex=ped$sex, famid=ped$famid)
#kinall <- kinship(pedall)
#kinall <- kinall*2
#save(kinall,file="KINSHIP_MATRIX.Rdata")
# ------------------------------------------------------
